---
- name: remove a specific cron job
  hosts: node1
  tasks:
    - name: remove cron job
      cron: 
        name:  "write message to file"
        cron_file: keep-alive-messages
        state: absent
        user: ansible
