---
- name: create apache vhost
  hosts: node1
  
  roles:
    - vhost

  post_tasks:
    - name: install contents from local file
      copy:
        src: files/html/
        dest: "/var/www/vhosts/{{ ansible_hostname }}" 


