---
- name: run task before role
  hosts: node1
  tasks:
    - name: update cache
      apt:
        update_cache: yes
  roles:
    - motd














#---
#- name: run a task before a role
#  hosts: all
#  pre_tasks:
#    - name: update yum cache
#      yum:
#        update_cache: yes
#  roles:
#    - motd
#
#
