---
# tasks file for vhost
- name: install http
  apt:
    name: apache2
    state: latest
- name: start and enable httpd
  service:
    name: apache2
    state: started
    enabled: true
- name: install vhost config file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache2

