---
- name: install web server
  hosts: node2
  tasks:
    - name: install apache2 on node2
      apt:
        name:
          - apache2
          - firewalld
        state: latest
    - name: install hi youssef!!
      copy:
        content: "Hello Youssef"
        dest: /var/www/html/index.html
    - name: start web
      service:
        name: apache2
        enabled: true
        state: started
    - name: start firewall
      service:
        name: firewalld
        enabled: true
        state: started
    - name: setting firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

- name: test web
  hosts: localhost
  become: on
  tasks:
    - name: connect to web server
      uri:
        url: http://node2
        return_content: yes
        status_code: 200

