---
- name: configure sudo
  hosts: node1
  vars_files:
    - vars/groups
    - vars/users
    - vars/defaults
  tasks:
    - name: add groups
      group:
        name: "{{ item.groupname }}"
      loop: "{{ groupname }}"
    - name: add users
      user:
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
      loop: "{{ users }}"
    - name: add SSH pub key
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', 'files/'+ item.username + '/id_rsa.pub') }}"
      loop: "{{ users }}"

    - name: allow group membres in sudo
      template:
        src: sudoers.j2
        dest: /etc/sudoers.d/sudogroups
        validate: 'visudo -cf %s'
        mode: 0440