---
- name: configure web
  hosts: node1
  tasks:
    - name: this is the {{ web_package }} package
      debug:
        msg: "Installing {{ web_package }}"
    - name: "Starting {{ web_service }}"
      debug:
        msg: "Starting {{ web_service }}"