---
- name: file copy module
  hosts: all
  tasks:
    - name: copy file
      copy:
        src: /etc/hosts
        dest: /tmp/hosts
    - name: add some line to /tmp/hosts
      blockinfile:
        path: /tmp/hosts
        block: |
          192.168.122.87 node1
          192.168.122.19 node2
        state: present
    - name: verify file checksum
      stat:
        path: /tmp/hosts
        checksum_algorithm: md5
      register: result
    - debug:
        msg: "The checksum of /tmp/hosts is {{ result.stat.checksum }}"
    - name: fetch a file
      fetch:
        src: /tmp/hosts
        dest: /tmp/














#---
#- name: file copy modules
#  hosts: all
#  tasks:
#  - name: copy file demo
#    copy:
#      src: /etc/hosts
#      dest: /tmp/
#  - name: add some lines to /tmp/hosts
#    blockinfile:
#      path: /tmp/hosts
#      block: |
#        192.168.4.110 host1.example.com
#        192.168.4.120 host2.example.com
#      state: present
#  - name: verify file checksum
#    stat:
#      path: /tmp/hosts
#      checksum_algorithm: md5
#    register: result
#  - debug:
#      msg: "The checksum of /tmp/hosts is {{ result.stat.checksum }}"
#  - name: fetch a file
#    fetch:
#      src: /tmp/hosts
#      dest: /tmp/
