- name: simple block example
  hosts: all
  tasks:
    - name: setting up http
      block:
      - name: installing http
        apt:
          name: apache2
          state: present
      - name: restart httpd
        service:
          name: apache2
          state: started
      when: ansible_distribution == "RedHat"
