---
- name: using  block
  hosts: node1
  tasks:
    - name: intended to be successful
      block:
        - name: remove a file
          shell:
            cmd: /usr/bin/rm /var/www/html/index.html
      rescue:
        - name: create a file
          shell:
            cmd: /usr/bin/touch /tmp/rescuefile
      always:
        - name: always write message
          shell:
            cmd: /usr/bin/logger hello










#- name: using blocks
#  hosts: all
#  tasks:
#    - name: intended to be successful
#      block:
#        - name: remove a file
#          shell:
#            cmd: /usr/bin/rm /var/www/html/index.html
#      rescue:
#        - name: create a file
#          shell:
#            cmd: /usr/bin/touch /tmp/rescuefile
#      always:
#        - name: always write a message to logs
#          shell:
#            cmd: /usr/bin/logger hello
#
