---
- name: when demo
  hosts: node1
  vars:
    supported_distros:
      - RedHat
      - CentOS
      - Fedora
  tasks:
    - name: install RH family specfic package
      apt:
        name: nginx
        state: present
      when: ansible_distribution in supported_distros








#---
#- name: when demo
#  hosts: all
#  vars:
#    supported_distros:
#      - Ubuntu
#      - CentOS
#      - Fedora
#  tasks:
#    - name: install RH family specific packages
#      yum:
#        name: nginx
#        state: present
#      when: ansible_distribution in supported_distros


