---
- name: database server is running
  hosts: all
  vars:
    database_packages:
      - mariadb-server
      - python3-PyMySQL
    mysql_password: "password"

  tasks:
    - name: mariadb packages are installed
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ database_packages }}"
      
















#---
#- name: install MariaDB
#  hosts: node1
#  vars:
#    mysql_root_password: "Password1"
#  tasks:
#    - name: install mariadb
#      apt:
#        name:
#          - mariadb-server
#          - python3-PyMySQL
#        state: latest
#    - name: start mariadb
#      service:
#        name: mariadb
#        enabled: true
#        state: started
#    - name: mysql_root_password
#      mysql_user:
#        login_user: root
#        login_password: "{{ mysql_root_password }}"
#        user: root
#        check_implicit_admin: true
#        password: "{{ mysql_root_password }}"
#        host: localhost
