---
- name: demo how register work
  hosts: all
  tasks:
    - name: show loop register
      shell: "echo {{ item }}"
      loop:
        - "one"
        - "two"
      register: echo
    - name: show register results
      debug:
        var: echo











#---
#- name: demo how register works
#  hosts: all
#  tasks:
#  - name: show loop register
#    shell: "echo {{ item }}"
#    loop:
#      - "one"
#      - "two"
#    register: echo
#  - name: show register results
#    debug:
#      var: echo
