---
- name: test register
  hosts: all
  vars:
    users:
      - youssef
  tasks:
    - shell: cat /etc/passwd
      register: passwd_contantd
    - debug:
        msg: echo "passwd contain user {{ users }}"
      when: passwd_contantd.stdout.find(users) != -1








#---
#- name: test register
#  hosts: all
#  tasks:
#    - shell: cat /etc/passwd
#      register: passwd_contents
#    - debug:
#        msg: echo "passwd contains user lisa"
#      when: passwd_contents.stdout.find('lisa') != -1
