---
- name: create a user using a variable
  hosts: all
  vars:
    user: lisa
  tasks:
    - name: create a user {{ user }}
      user:
        name: "{{ user }}"


---
- name: create user using var
  hosts: all
  vars:
    user: lisa
  tasks:
    - name: create a user {{ user }}
      user:
        name: "{{ user }}"
